# Generated by Django 4.1.2 on 2022-10-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_artiste_alter_artiste_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Artiste',
        ),
    ]
