# Generated by Django 4.1.2 on 2022-10-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_lyric_song_id_alter_song_artiste_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='las_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
    ]
